title: Dvan
description: A config-free static site generator for Vue
themeConfig:
  repo: evillt/dvan
  repoLabel: GitHub
  docsDir: docs
  displayAllHeaders: true
  nav:
    - text: Guide
      link: /guide/introduction
    - text: Config
      link: /config/
  sidebar:
    - title: Getting Started
      collapsable: false
      children:
        - /guide/introduction
        - /guide/quick-started
        - /guide/configuration
        - /guide/directory-structure
