title: Dvan
description: A config-free static site generator for Vue
themeConfig:
  displayAllHeaders: true
  nav:
    - text: Guide
      link: /guide/introduction
    - text: Config
      link: /config/
    - text: GitHub
      link: https://github.com/evillt/dvan
  sidebar:
    - title: Getting Started
      collapsable: false
      children:
        - /guide/introduction
        - /guide/quick-started
        - /guide/configuration
        - /guide/directory-structure
evergreen: true